version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ze_delivery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: